on:
  push:
    branches:
      - staging
    paths:
      - 'hs-contact-caddie/**'
      - '.github/workflows/**'
env:
  DEFAULT_ACCOUNT_ID: ${{ secrets.HUBSPOT_STAGING_ACCOUNT_ID }}
  DEFAULT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_STAGING_PERSONAL_ACCESS_KEY }}
  DEFAULT_CLI_VERSION: 7.8.0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HubSpot Project Action
        uses: HubSpot/hubspot-project-actions@v1.0.0
        with:
          project_dir: hs-contact-caddie
          profile: staging

